
server.port: 8081

spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    url: jdbc:mysql://localhost:3306/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    # username: cami
    username: root
    password: 
    # password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace